### ISSUE TITLE
WARNING and replication parameter in idtxl

### ISSUE THREAD

**Issue by peanutnim** [pwollstadt/IDTxl#100]
Dear idtxl Team,
Hi,I‘m a student utilizing idtxl for analyzing my research data.I have converted my data into a two-dimensional numpy array, and I am unsure how to incorporate the concept of replication in this context. Therefore, I am uncertain about the appropriate way to add replication.
During my analysis, I encountered the following warning message and would appreciate your assistance in understanding its meaning and addressing related concerns:

WARNING: Number of replications is not sufficient to generate the desired number of surrogates. Permuting samples in time instead.
maximum statistic, n_perm: 200

Could you please provide clarification regarding the meaning and implications of this warning message? What does it indicate when the number of replications is considered insufficient? How does idtxl handle this situation by permuting samples in time?

Additionally, I have been searching for documentation or information pertaining to the replication parameter in idtxl, but have been unable to find any specific details. Could you kindly provide information on how to set and adjust the replication parameter? What is the default value, and how does it impact the analysis?

After encountering the aforementioned warning message, does idtxl automatically adjust any settings or parameters? If so, could you please explain the automatic adjustments that occur after encountering this warning?

I am grateful for your time and support in addressing these concerns. As a student utilizing idtxl, your guidance would greatly contribute to my research analysis. Thank you for your dedication in developing and maintaining the idtxl.

Best regards,
Bernadetta Pitkin

**Comment by pwollstadt** [comment]
Hi Bernadette, The warning is not a problem, it just means IDTxl will generate the necessary surrogates not by permuting replications (the default), but permuting samples in time.

The number of replications is a property of your data. IDTxl accepts 3D data formats, where one dimension are the processes, one dimension are the samples in time, and one dimension are potential replications of your observation. For example, in an experimental setup, you may repeat the same experiment multiple times and each time collect a number of samples from the same sensors. That would give you such a 3D structure. If you don't have replications in your use case, this is not a problem. You just have to take care that you are providing enough samples for estimation (usually a few Thousand is great).

**Comment by mwibral** [comment]
Hi Bernadette,


if your code has to default to permutation in time, make sure you understand and choose the right of way of permuting in time. Not all options are OK for all use cases. It is typically best to choose a cut point and circularly shift things in time - rather than for example wildly permuting single samples. Could you let us know some more about your data so that we can give advice?


Best,

Michael


________________________________
