### ISSUE TITLE
Can't use plot_network function

### ISSUE THREAD

**Issue by 1191828365** [pwollstadt/IDTxl#106]
### Description

I encountered an error when running the code `plot_network(results=results, weights='max_te_lag', fdr=False)` in 
 example **Your first Information Network Inference with IDTxl** .

### Expected Behavior
Get a network plot.

### Actual Behavior
Got an error after I inputed `plot_network(results=results, weights='max_te_lag', fdr=False)`
```
qt. qpa. plugin: could not load the Qt platform plugin “xcb” in ””even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
Available platform plugins are: eglfs, minimal, minimalegl, offscreen, vnc,webgl, xcb.
Aborted (core dumped)
```
I set the export `QT_DEBUG_PLUGINS=1` then got a detailed description.
`Cannot load library /home/ss/miniconda3/envs/idtxl/plugins/platforms/libqxcb.so: (libxcb-icccm.so.4: cannot open shared object file: No such file or directory)`
`QLibraryPrivate::loadPlugin failed on "/home/ss/miniconda3/envs/idtxl/plugins/platforms/libqxcb.so: (libxcb-icccm.so.4: cannot open shared object file: No such file or directory)"`

The documents in /home/ss/miniconda3/envs/idtxl/plugins/platforms are like:
```
libqxcb.so
libqwebgl.so
libqvnc.so
libqoffscreen.so
libqminimalegl.so
libqminimal.so
libqeglfs.so
```
### Environment

- IDTxl-1.5(with infordynamics.jar was replaced as v1.6.1)
- Windows 11 64-bit
- java version "1.8.0_272"
- Python “3.10.13”
- JPype1 “1.5.0"

**Comment by pwollstadt** [comment]
Hi @1191828365 this seems to be a problem not directly related to IDTxl. I did a quick google search and found this amongst other threads: https://github.com/NVlabs/instant-ngp/discussions/300 
Maybe something in there helps?

I would close this issue as it does not seem to relate to a bug in IDTxl. Please re-open it if it turns out there is something wrong anyways. 

Thanks, Patricia
