### ISSUE TITLE
Issues in statistical testing

### ISSUE THREAD

**Issue by daehrlich** [pwollstadt/IDTxl#108]
The current version of IDTxl contains issues in the statistical testing.

Please wait for this issue to be marked as fixed before using the affected code features. For more information, see the linked pull request.

**Comment by JulesMitchell** [comment]
Thanks for your work on the IDTxl package. 

Is there any ETA that these bug fixes will be released in version 1.6?

**Comment by mwibral** [comment]
The bugfix has been merged into master. 
When testing/reviewing results please be aware that:
1) Our statistical tests in the default setting are hierarchical tests (target level -> source level, see  Novelli et al., Network Neuroscience, 2019; https://pubmed.ncbi.nlm.nih.gov/31410382/), keep this fact in mind when interpreting results.
2) FDR correction is not Bonferroni correction - you will typically find more false positives with FDR compared to Bonferroni.
3) The sequential max stats also has a slightly higher false positive rate than max stats.

**Comment by JulesMitchell** [comment]
Hi Michael, 

Thank you, and the team for merging the bugfix. On an unrelated point, I'm attempting to use the 'add_conditionals': 'faes" method, however, I get an IndexError "string index out of range" for the _lag_to_idx function. Must the min source/target lags be set to something specific for this to work?

I appreciate this is not the forum for such a question but I figured it best to post here as the google group hasn't seen any activity lately.

**Comment by mwibral** [comment]
Dear Jules,

we'll have a look. 

For the Faes method, a zero lag für die conditionals is used. You may
be able to add that manually.

Best,
Michael
