### ISSUE TITLE
ValueError when checking variables for JidtDiscreteMI

### ISSUE THREAD

**Issue by pietromarchesi** [pwollstadt/IDTxl#14]
The documentation for `JidtDiscreteMI` says that the variables `var1` and `var2` can be

> either a 2D numpy array where array dimensions represent [realisations x variable dimension] or a 1D array representing [realisations], array type can be float (requires discretisation) or int

But then in `_discretise_vars` it goes on to check that the variables are nonnegative by doing

```python
assert min(var1) >= 0, 'Minimum of var1 is smaller than 0.'
assert min(var2) >= 0, 'Minimum of var2 is smaller than 0.'
```
Which raises a `ValueError` if the variable is actually 2D. As the variable is required to be a numpy array, it should probably compute `var1.min()` instead. 

To reproduce:
```python
import numpy as np
from idtxl.estimators_jidt import JidtKraskovMI
x = np.random.randint(low=0, high=10, size=[100, 2])
y = np.random.randint(low=0, high=10, size=[100, 2])
jidt_mi = JidtDiscreteMI(settings={'discretise_method': 'none'})
jidt_mi.estimate(x, y)
```
Raises
```
Traceback (most recent call last):
  File "/home/pietro/Envs/basic36/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2910, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-26-8d417a12d2e1>", line 6, in <module>
    jidt_mi.estimate(x, y)
  File "/home/pietro/pythonprojects/IDTxl/idtxl/estimators_jidt.py", line 690, in estimate
    var1, var2 = self._discretise_vars(var1, var2)
  File "/home/pietro/pythonprojects/IDTxl/idtxl/estimators_jidt.py", line 212, in _discretise_vars
    assert min(var1) >= 0, 'Minimum of var1 is smaller than 0.'
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

I can submit a PR if you agree.

**Comment by jlizier** [comment]
Thanks Pietro - that's previously been changed on the develop branch (which will be merged back to master in future); I've validated that it's fine there and am closing the issue.

A couple of brief comments also:
1. the import line should be: `from idtxl.estimators_jidt import JidtDiscreteMI`
1. the constructor line also needs to set the proper alphabet size to 10 if you want to avoid getting another error after that one is addressed: `jidt_mi = JidtDiscreteMI(settings={'discretise_method': 'none'})`
