### ISSUE TITLE
Could not find a version that satisfies the requirement setup.py (from versions: ) No matching distribution found for setup.py

### ISSUE THREAD

**Issue by jpainam** [pwollstadt/IDTxl#24]
Hi,
I downloaded the latest IDTxl from github and I have `python 3.4.4`. When running `pip install setup.py`, I get this error
```python
Could not find a version that satisfies the requirement setup.py(from versions: )
No matching distribution found for setup.py
```
and when using `python install -e setup.py`, i get
```python 
setup.py should either be a path to a local project or a VCS url beginning with svn+, git+, hg+, or bzr+
```
What could be the problem?
Thank you

**Comment by pwollstadt** [comment]
Hi @jpainam, I couldn't reproduce the error on my machine, so could you try the following from within the IDTxl folder (the one that contains `setup.py`):

`pip install -e .` (pip takes a directory as argument, not the `setup.py`)

`python setup.py install` (you may have the arguments in the wrong order here)

Thanks!

**Comment by jpainam** [comment]
Thank you, it worked. but you need to update the the [documentation](https://github.com/pwollstadt/IDTxl/wiki/Installation-and-Requirements)

**Comment by pwollstadt** [comment]
I did, sorry about that and thanks for the hint
