### ISSUE TITLE
pytest unit test fails for test_neighbour_search_opencl.py

### ISSUE THREAD

**Issue by mwibral** [pwollstadt/IDTxl#32]
With a fresh install of IDTxl on:
Ubuntu 16.04.5
AMD Carrizo APU
amdgpu-pro 18.30
 I get the following failure when running the pytests:

================================================================ FAILURES ================================================================
____________________________________________________________ test_random_data ____________________________________________________________

    def test_random_data():
        """Smoke kNN test with big random dataset."""
        n_points = 1000
        n_dims = 5
        pointset1 = np.random.randn(n_points, n_dims).astype('float32')
        pointset2 = pointset1
    
        # Call MI estimator
        mi, dist1, npoints_x, npoints_y = EST_MI.estimate(
            pointset1, pointset2, n_chunks=1)
        # Call CMI estimator with pointset2 as conditional (otherwise the MI
        # estimator is called internally and the CMI estimator is never tested).
        cmi, dist2, npoints_x, npoints_y, npoints_c = EST_CMI.estimate(
            pointset1, pointset2, pointset2, n_chunks=1)
>       assert np.all(np.isclose(dist1, dist2)), (
            'High- and low-level calls returned different distances.')
E       AssertionError: High- and low-level calls returned different distances.
E       assert False
E        +  where False = <function all at 0x7f411888cf28>(array([ True,  True,  True, ...,  True,  True,  True]))
E        +    where <function all at 0x7f411888cf28> = np.all
E        +    and   array([ True,  True,  True, ...,  True,  True,  True]) = <function isclose at 0x7f41188781e0>(array([0.58077002, 0.91198087, 0.26068008, ..., 0.0625    , 0.0625    ,\n       0.0625    ]), array([0.58077002, 0.91198087, 0.26068008, ..., 0.0625    , 0.0625    ,\n       0.0625    ]))
E        +      where <function isclose at 0x7f41188781e0> = np.isclose

test_neighbour_search_opencl.py:157: AssertionError

**Comment by pwollstadt** [comment]
I could not replicate this. Does this problem persist? I would close this issue. Please reopen if the problem occurs again.
