### ISSUE TITLE
Absence of  New Data State in ResultsNetworkInference  Class 

### ISSUE THREAD

**Issue by DennisHarmah** [pwollstadt/IDTxl#33]
I have explored the ResultsNetworkInference class ,but i am finding it difficult to  get the  new state of the processed data after the  algorithms for network inference have been applied by the analyse_network() method. Please how can I return the new state of the data passed into the data class. For example I passed a data of shape 16x100x23  using dim_order , 'psr' .How can I get the new state of the data in the same dimension after the analysis of the network (eg. Using mTE algorithm). 

Thank you

**Comment by pwollstadt** [comment]
Hi @DennisHarmah, in general, IDTxl's network inference algorithms return directed networks representing, for example, the mTE between network nodes. So the output (e.g., from mTE analysis using `MultivariateTE().network_analysis()`, see [this line](https://github.com/pwollstadt/IDTxl/blob/de4ed33770311ba566c74d2f88fcafbecefcd6f5/demos/demo_multivariate_te.py#L18) in the demo script) is a network represented by its adjacency matrix. You can obtain this matrix by running the following on the returned results object:

```python 
adj_matrix = results.get_adjacency_matrix(weights='max_te_lag', fdr=False)
adj_matrix.print_matrix()
```

The data itself is not modified by the algorithm, so there is no new state of the data and the data object doesn't change after running it through the algorithm.

Let me know if this answers your question. Also consider moving this to [IDTxl's google groups](https://groups.google.com/forum/#!forum/idtxl), which is more appropriate for discussing usage and posting general questions. You can also write me an email to discuss this further. (Github issues are for tracking bugs in the code only. I will leave this open for now, in case there is something to report.)

**Comment by pwollstadt** [comment]
I am closing this issue because it has been inactive for a few months. If this isn't solved or needs further discussion, feel free to reopen or consult the [IDTxl mailing list](https://groups.google.com/forum/#!forum/idtxl). Thanks!
