### ISSUE TITLE
Installation misses copying gpuKnnKernelNoIdx.cl

### ISSUE THREAD

**Issue by pawarrick** [pwollstadt/IDTxl#37]
Environment
OS: Win64
Python 3.5.6
System RAM: 32GB
GPU: NVidia GeForce GTX 1080Ti 11GB
pyopencl: [pyopencl-2018.2.5+cl12-cp35-cp35m-win_amd64.whl](https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyopencl)
other required packages installed from pypi as "pip install package_x"
(Note that "pip install pyopencl" did appear to install corrrectly, but did not work at runtime, perhaps due to a missing dll)

Following the installation instructions (for GPU only to begin, ignoring CPU java components), and running the [wiki demo](https://github.com/pwollstadt/IDTxl/wiki#your-first-information-network-inference-with-idtxl)

```
#data.generate_mute_data(n_samples=1000, n_replications=5) # failed "pyopencl._cl.RuntimeError: clEnqueueReadBuffer failed: OUT_OF_RESOURCES"
data.generate_mute_data(n_samples=1000, n_replications=1) # succeeded
#data.generate_mute_data(n_samples=1000, n_replications=2) # failed out of resources
#data.generate_mute_data(n_samples=2000, n_replications=1) # failed out of resources
#data.generate_mute_data(n_samples=4000, n_replications=1) # failed out of resources
  
# b) Initialise analysis object and define settings
network_analysis = MultivariateTE()
settings = {
#            'cmi_estimator': 'JidtGaussianCMI',
              'cmi_estimator': 'OpenCLKraskovCMI',              
              'max_lag_sources': 5,
              'min_lag_sources': 1}
  
```
got the error
No such file or directory: 'C:\\ProgramData\\Anaconda3\\envs\\IDTxl\\lib\\site-packages\\idtxl\\gpuKnnKernelNoIdx.cl

I manually copied this file from master to the python environment that I created for IDTxl and then the demo did run.

Note also that I tried the demo, reducing the parameters in a few combinations (see above): the only successful run used the n_samples=1000, n_replications=1.  Also, n_samples = 4000 did work with 'max_lag_sources': 1.

Is this expected?   My GPU looks very lightly utilized at first glance.  I see now more discussion about this on issue #30

Many thanks.

**Comment by cspipaon** [comment]
Same issue here on Linux Manjaro 18.04, GTX 1050 Mobile.
