### ISSUE TITLE
TypeError: Ambiguous overloads found for infodynamics.measures.continuous.gaussian.MutualInfoCalculatorMultiVariateGaussian.setObservations(numpy.ndarray,numpy.ndarray)

### ISSUE THREAD

**Issue by cspipaon** [pwollstadt/IDTxl#38]
Dear all,

Running Linux Manjaro 18.0.4. Previously, using Windows 10 the same error described below occurred.

At the moment I cannot run JIDT estimators. I attempted solution posted in https://github.com/pwollstadt/IDTxl/issues/26#issuecomment-454148394 without any luck. Previously I had the same error as in the linked issue #26 . Now, trying the solution posted in the link I get the following error when running `demo_bivariate_mi.py`:

<pre>Traceback (most recent call last):
  File &quot;demos/demo_bivariate_mi.py&quot;, line 18, in &lt;module&gt;
    results = network_analysis.analyse_network(settings=settings, data=data)
  File &quot;/home/carlos/IDTxl/IDTxl/idtxl/bivariate_mi.py&quot;, line 151, in analyse_network
    settings, data, targets[t], sources[t])
  File &quot;/home/carlos/IDTxl/IDTxl/idtxl/bivariate_mi.py&quot;, line 272, in analyse_single_target
    self._include_source_candidates(data)
  File &quot;/home/carlos/IDTxl/IDTxl/idtxl/network_inference.py&quot;, line 518, in _include_source_candidates
    conditional=conditional_realisations)
  File &quot;/home/carlos/IDTxl/IDTxl/idtxl/estimator.py&quot;, line 330, in estimate_parallel
    results[i] = self.estimate(**chunk_data)
  File &quot;/home/carlos/IDTxl/IDTxl/idtxl/estimators_jidt.py&quot;, line 1345, in estimate
    return self.est_mi.estimate(var1, var2)
  File &quot;/home/carlos/IDTxl/IDTxl/idtxl/estimators_jidt.py&quot;, line 1275, in estimate
    self.calc.setObservations(var1, var2)
TypeError: Ambiguous overloads found for infodynamics.measures.continuous.gaussian.MutualInfoCalculatorMultiVariateGaussian.setObservations(numpy.ndarray,numpy.ndarray) between:
	public void infodynamics.measures.continuous.MutualInfoMultiVariateCommon.setObservations(double[][],double[][]) throws java.lang.Exception
	public void infodynamics.measures.continuous.MutualInfoMultiVariateCommon.setObservations(double[],double[]) throws java.lang.Exception

	at findOverload(native/common/jp_method.cpp:214)
	at findOverload(native/common/jp_method.cpp:245)
	at invoke(native/common/jp_method.cpp:253)
	at __call__(native/python/pyjp_method.cpp:142)
</pre>

My environment's packages:
<pre># packages in environment at /home/carlos/anaconda3/envs/idtxl_jidt2:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
appdirs                   1.4.3                      py_1    conda-forge
bzip2                     1.0.6             h14c3975_1002    conda-forge
ca-certificates           2019.6.16            hecc5488_0    conda-forge
certifi                   2019.6.16                py37_0    conda-forge
cycler                    0.10.0                     py_1    conda-forge
dbus                      1.13.6               he372182_0    conda-forge
decorator                 4.4.0                      py_0    conda-forge
expat                     2.2.5             he1b5a44_1003    conda-forge
fontconfig                2.13.1            he4413a7_1000    conda-forge
freetype                  2.10.0               he983fc9_0    conda-forge
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
glib                      2.58.3            h6f030ca_1001    conda-forge
gst-plugins-base          1.14.5               h0935bb2_0    conda-forge
gstreamer                 1.14.5               h36ae1b5_0    conda-forge
h5py                      2.9.0           nompi_py37hf008753_1102    conda-forge
hdf5                      1.10.4          nompi_h3c11f04_1106    conda-forge
icu                       58.2              hf484d3e_1000    conda-forge
idtxl                     1.0                       dev_0    &lt;develop&gt;
jpeg                      9c                h14c3975_1001    conda-forge
jpype1                    0.7              py37h9de70de_0    conda-forge
kiwisolver                1.1.0            py37hc9558a2_0    conda-forge
libblas                   3.8.0               10_openblas    conda-forge
libcblas                  3.8.0               10_openblas    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
libiconv                  1.15              h516909a_1005    conda-forge
liblapack                 3.8.0               10_openblas    conda-forge
libopenblas               0.3.6                h6e990d7_4    conda-forge
libpng                    1.6.37               hed695b0_0    conda-forge
libstdcxx-ng              9.1.0                hdf63c60_0  
libuuid                   2.32.1            h14c3975_1000    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxml2                   2.9.9                h13577e0_1    conda-forge
mako                      1.0.10                     py_0    conda-forge
markupsafe                1.1.1            py37h14c3975_0    conda-forge
matplotlib                3.1.1                    py37_0    conda-forge
matplotlib-base           3.1.1            py37hfd891ef_0    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
networkx                  2.3                        py_0    conda-forge
numpy                     1.16.4           py37h95a1406_0    conda-forge
ocl-icd                   2.2.12            h14c3975_1003    conda-forge
openblas                  0.3.6                h6e990d7_4    conda-forge
openssl                   1.1.1c               h516909a_0    conda-forge
pcre                      8.41              hf484d3e_1003    conda-forge
pip                       19.1.1                   py37_0    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
pyopencl                  2019.1           py37h9de70de_0    conda-forge
pyparsing                 2.4.0                      py_0    conda-forge
pyqt                      5.9.2            py37hcca6a23_0    conda-forge
python                    3.7.3                h33d41f4_1    conda-forge
python-dateutil           2.8.0                      py_0    conda-forge
pytools                   2019.1.1                   py_0    conda-forge
qt                        5.9.7                h52cfd70_2    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
scipy                     1.3.0            py37h921218d_0    conda-forge
setuptools                41.0.1                   py37_0    conda-forge
sip                       4.19.8          py37hf484d3e_1000    conda-forge
six                       1.12.0                py37_1000    conda-forge
sqlite                    3.29.0               hcee41ef_0    conda-forge
tk                        8.6.9             hed695b0_1002    conda-forge
tornado                   6.0.3            py37h516909a_0    conda-forge
wheel                     0.33.4                   py37_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
zlib                      1.2.11            h14c3975_1004    conda-forge
</pre>

And the `java -version` output:
<pre>openjdk version &quot;1.8.0_222&quot;
OpenJDK Runtime Environment (build 1.8.0_222-b05)
OpenJDK 64-Bit Server VM (build 25.222-b05, mixed mode)
</pre>

Please let me know if you have any suggestions and/or need further information.

Thanks,
Carlos

**Comment by kozachynskyi** [comment]
Thank to author for immence work. Unfortunately we have a same error: Windows 10.
``
java version "1.8.0_192"
Java(TM) SE Runtime Environment (build 1.8.0_192-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.192-b12, mixed mode)
``

**Comment by pwollstadt** [comment]
Hi all, following [this discussion](https://groups.google.com/forum/#!topic/idtxl/plM5HeRZ6l4) in the google group, I can reproduce the error when using JPype1 0.7 (as is also installed in  @cspipaon's environment). I have to look into what changed in this version of JPype1, for now you may want to install the previous release version with

```bash
conda install -c conda-forge jpype1==0.6.3
```

Let me know if this fixes the error.

**Comment by Luzi12** [comment]
perfect. thx. it is working.

**Comment by jlizier** [comment]
Status update: as you see above we have a fix now on a development branch such that either JPype 0.7 or earlier can be used; will be integrating that through in the near future and will close the issue then.

**Comment by mwibral** [comment]
Hi Joe,

I suppose it's*jpype1* 0.7 or earlier (not jpype)?

At least the package jpype1 is what I always install.

Best,

Michael

**Comment by jlizier** [comment]
Yes, you're absolutely right, JPype 1.

Apologies for the delay on the PR, we got caught down a rabbit hole on a
related investigation. Will send tomorrow...

--joe
+61 408 186 901 (Au mobile)
