### ISSUE TITLE
Rare Error ConvergenceExceptionPyRaisable

### ISSUE THREAD

**Issue by aleksejs-fomins** [pwollstadt/IDTxl#40]
Hi, I am encountering a rare error in MultivariateMI. My dataset has 1 sample, 12 processes, ~100 repetitions. min and max lag is set to 0 - I'm only interested in instantainous MI for this run. Most analyse_target calls return with no problem, but occasionally I get this error. Any suggestions?

`'PicklingError("Can't pickle <class 'jpype._jexception.infodynamics.utils.commonsmath3.exception.ConvergenceExceptionPyRaisable'>: it's not found as jpype._jexception.infodynamics.utils.commonsmath3.exception.ConvergenceExceptionPyRaisable",)'`

Thanks,
Aleksejs

**Comment by pwollstadt** [comment]
Hi Aleksejs, I will close this because it has been inactive for a long time. Please let us know if you have more information on this problem or ideally a code example that triggers this behaviour reliably. Feel free to reopen this issue any time.
