### ISSUE TITLE
infodynamics.jar isn't installed correctly

### ISSUE THREAD

**Issue by Tacha-S** [pwollstadt/IDTxl#41]
I tried to install this package following the [installation guide](https://github.com/pwollstadt/IDTxl/wiki/Installation-and-Requirements).
But an error similar to #9 and #26 occurred in the [demo script](https://github.com/pwollstadt/IDTxl/blob/master/demos/demo_multivariate_te.py).
When I checked the site-package of python, `infodynamics.jar` wasn't installed, so when I copied it from `idtxl/infodynamics.jar`, the error disappeared. 😉

**Comment by pwollstadt** [comment]
Thank you! This is a bug in `setup.py`, which is fixed in the development branch (9d48ee74fe00d01bdf346db4553fe9f383299172) and will be in the next release.
