### ISSUE TITLE
Could you document how you handle continuous data? 

### ISSUE THREAD

**Issue by alexlenail** [pwollstadt/IDTxl#48]
This would make a helpful section in the [theoretical introduction](https://github.com/pwollstadt/IDTxl/wiki/Theoretical-Introduction). 

Alternatively, could you link to a paper which describes the approach taken by this package?

**Comment by pwollstadt** [comment]
Hi, for continuous data, we use the estimator by [Kraskov et al., 2004, Phys Rev E 69, 066138](https://journals.aps.org/pre/abstract/10.1103/PhysRevE.69.066138). We currently reference the paper in the (README)[https://github.com/pwollstadt/IDTxl#key-references] and the [docs](http://pwollstadt.github.io/IDTxl/html/idtxl_estimators.html#jidt-estimators-cpu) for the estimators. I will also add this info to the theoretical introduction, you are right, this is missing there. Thanks for the pointer! Best, Patricia

**Comment by pwollstadt** [comment]
Added a section on currently available estimators. Please comment or reopen if something is missing. 
Thanks, Patricia
