### ISSUE TITLE
convertStrings

### ISSUE THREAD

**Issue by jdbuffalo** [pwollstadt/IDTxl#49]
Below is a copy of the error I obtained when trying to follow the provided BivariateTE example.

from idtxl.bivariate_te import BivariateTE
from idtxl.data import Data
data = Data()
data.generate_mute_data(n_samples=1000, n_replications=5)
Adding data with properties: 5 processes, 1000 samples, 5 replications
overwriting existing data
network_analysis = BivariateTE()
settings = {'cmi_estimator': 'JidtGaussianCMI',
...             'max_lag_sources': 5,
...             'min_lag_sources': 1
...             }
... 
results = network_analysis.analyse_network(settings=settings, data=data)
####### analysing target with index 0 from list [0, 1, 2, 3, 4]
C:\Python\Python38-32\lib\site-packages\jpype\_core.py:202: UserWarning: 
-------------------------------------------------------------------------------
Deprecated: convertStrings was not specified when starting the JVM. The default
behavior in JPype will be False starting in JPype 0.8. The recommended setting
for new code is convertStrings=False.  The legacy value of True was assumed for
this session. If you are a user of an application that reported this warning,
please file a ticket with the developer.
-------------------------------------------------------------------------------
  warnings.warn("""
Process finished with exit code -1073740791 (0xC0000409)

**Comment by mwibral** [comment]
Dear jdbuffalo,

just a quick check - you are indeed using jpype1 as required, not jpype, 
are you?

Best,

Michael

**Comment by jdbuffalo** [comment]
Michael,

Correct, I am using jpype1. 

Best,
Josh

**Comment by pwollstadt** [comment]
Hi @jdbuffalo, could you check the version of JPype1 you're running? There was some problem after an update to JPype1 (see #38). Thanks to a fix by @jlizier this should work in the newest release ([v1.1](https://github.com/pwollstadt/IDTxl/releases/tag/v1.1)) or by downgrading JPype1 to v0.6.3 as described in the [conda installation instructions](https://github.com/pwollstadt/IDTxl/wiki/Installation-and-Requirements#anaconda-installation). 

Let me know if that helped.

Thanks, Patricia

**Comment by pwollstadt** [comment]
Will close this due to inactivity. Fell free to reopen if necessary.
