### ISSUE TITLE
Are the information units in nats?

### ISSUE THREAD

**Issue by dizcza** [pwollstadt/IDTxl#51]
I was searching for keywords nats and bits in your project and found both keys. It's not stated clearly in the documentation what the default units are for all your estimators.
I suppose it's nats.

**Comment by pwollstadt** [comment]
Yes, for the KSG estimator it's nats. For the discrete estimators in the JIDT backend, I would suspect it's also nats. Maybe @jlizier can quickly answer this? 
Best, Patricia

**Comment by jlizier** [comment]
Hi all, yes the units are:
- KSG estimator (JIDT and GPU): nats
- Linear-Gaussian estimator: nats
- Discrete: bits

**Comment by dizcza** [comment]
Thank you.
You can close the issue.

**Comment by jlizier** [comment]
Thanks @dizcza -- let's leave it open until documentation has this.
I'm not so familiar with the layout - @LNov or @pwollstadt can you guys slot the above info in where it's appropriate?
