### ISSUE TITLE
MI and CMI estimators add noise to the same data more than once

### ISSUE THREAD

**Issue by pmediano** [pwollstadt/IDTxl#6]
Some MI and CMI estimators do in-place addition to add noise to the data (e.g. `estimators_mi.py`, line 89, `var1 += np.random.normal(...)`), which modifies the original variable. This is a problem because the estimator will keep adding more noise to the data if called multiple times.

**Comment by pwollstadt** [comment]
Fixed for JIDT estimators in commit 025a213def6bc02878c2904b170d26594487c56e. Also fixed in @pmediano's new OpenCL estimators (commits 4757d2bc21347bb4df2a9e3e2610ec718c9d9342 and c8a1b22911504dd3a21e3594cfa724bc26a1b9a2)
