### ISSUE TITLE
Estimating bivariate_te using data frame

### ISSUE THREAD

**Issue by AviralKumarTiwari** [pwollstadt/IDTxl#72]
Dear Sir/Madam,
Can you please provide a demo showcasing the application of proposed methods using data frame from Panda? When I try I am getting error. Also not able to see the structure of the data which is generated in your demos using following lines:
# a) Generate test data
data = Data()
data.generate_mute_data(n_samples=1000, n_replications=5)

It would be great for new users to showcase the application using realtime data.

import pandas as pd

#np.random.seed(1945)
#x = np.random.randint(0, 2, size=1000)
#y = np.random.randint(0, 2, size=1000)

data = pd.read_excel (r'C:\ACC.xlsx', sheet_name='Sheet1',parse_dates=['date'], index_col='date')
data.head()

**Comment by pwollstadt** [comment]
Hi @AviralKumarTiwari, what error do you get exactly?

IDTxl does accept pandas data frames as input to the Data class, which goes into the network inference algorithms (you can't pass a pandas data frame directly though). Here is a modified version of the bivariate TE demo script (it also shows how to access the attribute holding the actual data within the Data object through `data._data`):

```python
# Import classes
from idtxl.bivariate_te import BivariateTE
from idtxl.data import Data
from idtxl.visualise_graph import plot_network
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

# a) Generate test data
cov = 0.4
lag = 1
n = 1000
source = np.random.randn(n+lag)
target = cov * source + (1-cov) * np.random.randn(n+lag)
np.random.seed(42)
df = pd.DataFrame({
    'source': source[lag:],
    'target': target[:-lag]
})
print(df.shape)
print(df.head())
data = Data(df, dim_order='sp')
print(data._data.shape)

# b) Initialise analysis object and define settings
network_analysis = BivariateTE()
settings = {'cmi_estimator': 'JidtGaussianCMI',
            'max_lag_sources': 5,
            'min_lag_sources': 1}

# c) Run analysis
results = network_analysis.analyse_network(settings=settings, data=data)

# d) Plot inferred network to console and via matplotlib
results.print_edge_list(weights='max_te_lag', fdr=False)
plot_network(results=results, weights='max_te_lag', fdr=False)
plt.show()
```

**Comment by AviralKumarTiwari** [comment]
Many thanks dear Prof. for this help.
I was able to work with the example that you had provided.

Kind regards
Aviral
