### ISSUE TITLE
Significance testing using my own surrogate data

### ISSUE THREAD

**Issue by nicrie** [pwollstadt/IDTxl#76]
First of all thank you for creating this very neat and comprehensive open-source package.

I want to calculate multivariate TE for a single target. Since I don't have any replicates for my time series, `IDTxl` chooses permutation in time as a fallback. I see that you have implemented a whole range of awesome permutation techniques, but it seems that none of them is appropriate for my case. I have to assume that my time series contain several different frequencies which are not known a priori. The most proper significance test in my case seems to be surrogate testing using iterative amplitude adjusted Fourier transform (IAAFT) surrogates. 

Is there currently any way of doing the following using `IDTxl`?
1. Performing significance testing using IAAFT surrogates
2. Providing pre-computed surrogates to IDTxl which (i) are used for significance testing and (ii) deactivate the automatic computation of permutated time series in order to save computation time

If not, would there be an interest in implementing any of these? Without promising anything, I could give it a try though.

**Comment by pwollstadt** [comment]
Hi @nicrie, there is currently no straightforward way to pass your own surrogate data to IDTxl. We are working on integrating spectral TE estimation to the toolbox as described in [Pinzuti (2020),  PLoS Comput Biol 16(12): e1008526](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1008526). There is a [feature branch](https://github.com/pwollstadt/IDTxl/tree/feature_spectral_te), we have not fully integrated and which is still in a bit of a beta state. Maybe this is helpful to you or gives you some ideas on how to integrate IAAFT surrogates (there is a [demo script](https://github.com/pwollstadt/IDTxl/blob/feature_spectral_te/demos/demo_multivariate_spectral_te.py) illustrating how to use the code).

We are always happy about contributions to the toolbox. So if you want to give the implementation a try, let me know, and I can give you some pointers on where to start.

**Comment by pwollstadt** [comment]
I will close this issue since it is not exactly about a problem with the code. Feel free to reopen any time.
