### ISSUE TITLE
Cannot create Data instance

### ISSUE THREAD

**Issue by fishbacp** [pwollstadt/IDTxl#79]
Running Python3.9 on Mac OS 11.6.1 with most recent version of IDTxl. The simple example below fails with the message 
 
 `NameError: name 'Data' is not defined`

```
from idtxl import *
from idtxl.multivariate_te import MultivariateTE

data = Data()
data.generate_mute_data(100, 5)
settings = {
    'cmi_estimator':  'JidtKraskovCMI',
    'n_perm_max_stat': 200,
    'n_perm_min_stat': 200,
    'n_perm_omnibus': 500,
    'n_perm_max_seq': 500,
    'max_lag_sources': 5,
    'min_lag_sources': 2
    }
network_analysis = MultivariateTE()
results = network_analysis.analyse_network(settings, data)
```

**Comment by pwollstadt** [comment]
Hi @fishbacp, you have to import the Data class using `from idtxl.data import Data`. You may want to have a look at the [demos](https://github.com/pwollstadt/IDTxl/tree/master/demos) to get started.
