### ISSUE TITLE
compare_within

### ISSUE THREAD

**Issue by axelhutt** [pwollstadt/IDTxl#89]
Dear all,

I would like to compare statistically AIS in a network in two experimental conditions and found the compare_within function. Is this the right function to do this ? If yes, what are the results network_a and network_b , where do I get them from ? It would be great to have an explaining simple example code which demonstrates the usage.

**Comment by pwollstadt** [comment]
Hi Axel, for details on the comparison functions have a look at [this](https://github.com/pwollstadt/IDTxl/wiki/Statistical-comparison-between-sets-of-networks) wiki page, which also provides example code. In general, the network comparison works only on TE estimates. For now there is no functionality to compare AIS estimates in IDTxl.

**Comment by pwollstadt** [comment]
Hi Axel, I will close this issue. Please let me know if you have further questions on the statistics.
