### ISSUE TITLE
TypeError / JidtGaussianTE

### ISSUE THREAD

**Issue by Essy13** [pwollstadt/IDTxl#91]
Hi,
I am not yet very familiar with the package. I try to use the JidtGaussianTE estimator and I receive the following:

![image](https://user-images.githubusercontent.com/127252126/223553780-2138a105-9869-482b-94aa-9cdf3164df00.png)

I am practically just trying with demo code now (but was same error with own data). 
What am I doing wrong? :

![image](https://user-images.githubusercontent.com/127252126/223553959-6afad20b-2632-4115-a45a-a85f4011cd3a.png)

**Comment by Essy13** [comment]
I guess I cannot use this JidtGaussianTE just replacing JidtGaussianCMI in the settings. Can I have the network analysis for all pairs using JidtGaussianTE estimator?

**Comment by pwollstadt** [comment]
Hi, when using the network analysis as shown in the script, you have to provide a CMI estimator. You will get the multivariate TE estimation with the Gaussian estimator when running the script and specifying JidtGaussianCMI as estimator. For details on how the algorithm works, have a look at [this introduction](https://github.com/pwollstadt/IDTxl/wiki/Theoretical-Introduction) in the wiki.

The JidtGaussianTE estimator is intended as a more low-level estimator to directly estimate TE between two time series when the relevant histories are known. You can have a look at this and the following lines in the demo script on the implemented estimators: https://github.com/pwollstadt/IDTxl/blob/16c6cc52e31ec79f8ec18cd4ea107a7b76525ca2/demos/demo_core_estimators.py#L66.

**Comment by Essy13** [comment]
Thank you very much for your reply. I can run the JidtGaussianTE estimator the above described way.
I noticed in case of the network analysis that there are cases when the connection is indicated with a double ended arrow. I assume it means that there are significant conditional mutual information into both direction. However I am wondering that the time lag on the arrow is relevant for which of the two cases.

**Comment by pwollstadt** [comment]
Hi @Essy13, yes, the double-ended error means that there is TE in both directions. I would check the console output together with the Figure (e.g., by running results.print_edge_list(weights='max_te_lag', fdr=False), see also the [Tutorial](https://github.com/pwollstadt/IDTxl/wiki/The-Results-Class#resultsnetworkinference) in the Wiki). The lags describe the estimated delay between the two processes and is not related to the strength of the information transfer. The delay just describes how many time steps it takes for information to be transferred from one process to the other.
