### ISSUE TITLE
NameError: name 'jp' is not defined

### ISSUE THREAD

**Issue by AdelleBernal** [pwollstadt/IDTxl#92]
Excellent analyses tool!
Just started using this, and I am getting:

`NameError: name 'jp' is not defined`

when running the `demo_multivariate_te.py` and `demo_bivariate_te.py`.

**Comment by pwollstadt** [comment]
This means, IDTxl wasn't able to import JPype1 to access JIDT estimators that are implemented in Java. Make sure you have JPype1 installed as described [here](https://github.com/pwollstadt/IDTxl/wiki/Installation-and-Requirements). To be on the save side, try installing JPype version 0.6.3 or 0.7. Let me know if you continue to have problems with the package.
