### ISSUE TITLE
granger causality not implemented?

### ISSUE THREAD

**Issue by AtomicNess123** [pwollstadt/IDTxl#93]
Hi, and excellent work on this toolbox! I read the docs page where it says:

```
For network inference:
multivariate transfer entropy (TE)/Granger causality (GC)

```

However I couldn't find GC (Granger Causality) code in the toolbox. has it been implemented?

**Comment by pwollstadt** [comment]
Hello, to estimate granger causality, you can use the JIDTGaussianCMI estimator (see this [tutorial page](https://github.com/pwollstadt/IDTxl/wiki/CMI-Estimators#jidt-estimators) on estimators implemented in IDTxl and how to use them). 

I will close this issue as it does not concern a problem with the code. If you have further questions on how to use IDTxl, please refer to the [google mailing list](https://groups.google.com/forum/#!forum/idtxl). Thanks!
