### ISSUE TITLE
Why three sources when only two?

### ISSUE THREAD

**Issue by AdelleBernal** [pwollstadt/IDTxl#95]
When computing TE between just two arrays, I get this:

```
####### analysing target with index 1 from list [0, 1]

Target: 1 - testing sources [0]

---------------------------- (1) include target candidates
candidate set: [(1, 1), (1, 2), (1, 3)]
```

What does (1,3) mean?

**Comment by pwollstadt** [comment]
Hello, the candidate set shown is a list of potentially informative variables in the past of the target. Each variable is described by a process id and a time lag, in your case (1, 3) indicates the variable in process 1 (the target) with a lag of 3 time steps, relative to the current value (the point in time in the target process, into which information is potentially transferred). 
In case, you haven't had a look yet, the wiki contains more information on how the algorithm works, e.g., an [overview](https://github.com/pwollstadt/IDTxl/wiki#theoretical-background) and a short theoretical [introduction](https://github.com/pwollstadt/IDTxl/wiki/Theoretical-Introduction).

**Comment by pwollstadt** [comment]
I will close this issue as it does not concern a problem with the code. If you have further questions on how to use IDTxl, please refer to the [google mailing list](https://groups.google.com/forum/#!forum/idtxl). Thanks!
