### ISSUE TITLE
plot_network

### ISSUE THREAD

**Issue by peanutnim** [pwollstadt/IDTxl#96]
I hope this email finds you well. I have been using the IDTxl package for some research and I have a question about the order of nodes in the directed graph produced by the plot_network function.

Specifically, I am wondering if the order of nodes in the directed graph is based on the order of variables in the imported data file. I would appreciate any clarification on this matter.

Thank you for your time and assistance.

**Comment by pwollstadt** [comment]
Hello, yes, the numbering of the nodes corresponds to the numbering of processes in the input data.

As this issue does not concern a ploblem with the code, I will close it. If you have further questions on how to use IDTxl, please refer to the [google mailing list](https://groups.google.com/forum/#!forum/idtxl). Thanks!
